runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /
  static_files: www/style.css
  upload: www/style.css
  
- url: /images
  static_dir: static/images

- url: /
  static_dir: www
  
